version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./rag_engine:/app/rag_engine
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

volumes:
  mongo_data: